### ISSUE TITLE
Data ingestion give error message after update to latest version

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-containers#15]
**Describe the bug**
I tried to ingest data, based on the example https://i2group.github.io/analyze-containers/content/ingest_config_dev.html. 

**To Reproduce**
I imported quite often some example data on this way. But after the latest update it give the error below.

```
vscode ➜ /home/sdor/analyze-containers-280 $ manage-data -c config-demo -t sources
ok -- validation done

#----------------------------------------------------------------------
# Checking 'config-demo' deployment is live
#----------------------------------------------------------------------
Deployment is live

#----------------------------------------------------------------------
# Running /opt/analyze-containers/configs/config-demo/configuration/ingestion/scripts/create-ingestion-sources
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Adding Information Store Ingestion Source(s)
#----------------------------------------------------------------------
> INFO  [EtlToolkitUtility] - Java version: 17.0.9 (Eclipse Adoptium - OpenJDK 64-Bit Server VM)
Exception in thread "main" java.lang.IllegalStateException: The 'Database_Versions' table does not exist.
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.determineVersionTableSchema(DatabaseVersionCheck.java:180)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.retrieveVersionNumberFromVersionTable(DatabaseVersionCheck.java:150)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.getDatabaseVersionInfo(DatabaseVersionCheck.java:94)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.getVersionInfo(DatabaseVersionCheck.java:60)
        at com.i2group.disco.infostore.importer.internal.EtlToolkitUtility.checkToolkitAndDatabaseSameVersion(EtlToolkitUtility.java:32)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.createIngestionSource(IngestionSourceCreatorCLI.java:87)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.run(IngestionSourceCreatorCLI.java:66)
        at com.i2group.disco.infostore.cli.internal.CommandLineExecutor.execute(CommandLineExecutor.java:181)
        at com.i2group.disco.infostore.cli.internal.CommandLineExecutor.execute(CommandLineExecutor.java:148)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.execute(IngestionSourceCreatorCLI.java:62)
        at com.i2group.disco.infostore.importer.internal.EtlToolkitIngestionSourceCreatorCLI.main(EtlToolkitIngestionSourceCreatorCLI.java:23)
> INFO  [EtlToolkitUtility] - Java version: 17.0.9 (Eclipse Adoptium - OpenJDK 64-Bit Server VM)
Exception in thread "main" java.lang.IllegalStateException: The 'Database_Versions' table does not exist.
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.determineVersionTableSchema(DatabaseVersionCheck.java:180)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.retrieveVersionNumberFromVersionTable(DatabaseVersionCheck.java:150)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.getDatabaseVersionInfo(DatabaseVersionCheck.java:94)
        at com.i2group.disco.infostore.upgrade.internal.DatabaseVersionCheck.getVersionInfo(DatabaseVersionCheck.java:60)
        at com.i2group.disco.infostore.importer.internal.EtlToolkitUtility.checkToolkitAndDatabaseSameVersion(EtlToolkitUtility.java:32)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.createIngestionSource(IngestionSourceCreatorCLI.java:87)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.run(IngestionSourceCreatorCLI.java:66)
        at com.i2group.disco.infostore.cli.internal.CommandLineExecutor.execute(CommandLineExecutor.java:181)
        at com.i2group.disco.infostore.cli.internal.CommandLineExecutor.execute(CommandLineExecutor.java:148)
        at com.i2group.disco.infostore.importer.internal.IngestionSourceCreatorCLI.execute(IngestionSourceCreatorCLI.java:62)
        at com.i2group.disco.infostore.importer.internal.EtlToolkitIngestionSourceCreatorCLI.main(EtlToolkitIngestionSourceCreatorCLI.java:23)
```

**Expected behavior**
I expect no error messages.

**Screenshots**
See the code block above.

**Hardware and Software information**
Fill in the following information:

- OS: Windows
- Version: 2.8.0
- i2 Analyze version: 4.4.3 
- Environment type: config-dev
- Deployment pattern: i2c_istore,

**Additional context**
I didn't copy the files again to the i2a-data folder.

**Comment by sdorresteijn88** [comment]
I ran deploy -t clean command, now it's working fine.
